spring:
  profiles:
    active: dev # Cambiar según el entorno
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  secret: "a3nR4Jw7VzXp9LkQ2sFgUiZyBcDeHt9NmLp0xQvWsYkR8hFgTzZpN1kV6c3mXoLq"

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/proaudio_channels?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: Maiescuel8042.
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.proaudiochannels@gmail.com
    password: fsnb qycy vkuc wkkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    port: 8080
  cron:
    project-status: "0 * * * * *" #executing every minute
  app-base-url: http://localhost:5173

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/proaudio_channels?useSSL=false&serverTimezone=UTC
    username: root
    password: Usr.Tst1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.proaudiochannels@gmail.com
    password: fsnb qycy vkuc wkkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    port: 8080
  cron:
    project-status: "0 0 8,20 * * *" #executing at 8am and 8pm everyday
  app-base-url: https://proaudiochannels.com.uy:8443

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://db-servidor:3306/qrapp_prod
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.proaudiochannels@gmail.com
    password: fsnb qycy vkuc wkkh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    port: 80
  cron:
    project-status: "0 0 8,20 * * *" #executing at 8am and 8pm everyday
  app-base-url: https://proaudiochannels.com.uy:8443
